config:
  in_tpl: proto.tpl
  out_dir: ../db/data
  go_package: db/data;data
  package: db.data;
db:
  db_name: data
  db_tables: []
  dsn: root:123456@tcp(127.0.0.1:3306)/data?charset=utf8mb4&parseTime=true  